// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef KDEVEXECUTEBROWSER_VERSION_H
#define KDEVEXECUTEBROWSER_VERSION_H

#include <kdeversion.h>

#define KDEVEXECUTEBROWSER_MAJOR_VERSION @KDEVEXECUTEBROWSER_VERSION_MAJOR@
#define KDEVEXECUTEBROWSER_MINOR_VERSION @KDEVEXECUTEBROWSER_VERSION_MINOR@
#define KDEVEXECUTEBROWSER_PATCH_VERSION @KDEVEXECUTEBROWSER_VERSION_PATCH@

#define KDEVEXECUTEBROWSER_VERSION_STR "@KDEVEXECUTEBROWSER_VERSION_MAJOR@.@KDEVEXECUTEBROWSER_VERSION_MINOR@.@KDEVEXECUTEBROWSER_VERSION_PATCH@"

#define KDEVEXECUTEBROWSER_VERSION KDE_MAKE_VERSION(@KDEVEXECUTEBROWSER_VERSION_MAJOR@, @KDEVEXECUTEBROWSER_VERSION_MINOR@, @KDEVEXECUTEBROWSER_VERSION_PATCH@)

#endif
